version: "3"
services:
  buddy:
    build: ./
    ports:
      - "8080:8080"
    env_file:
      - docker/list.env
    depends_on:
      - redis

  redis:
    image: redis:5.0.3-alpine
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
